# Generated by Django 5.0.7 on 2024-07-27 09:10

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='name',
            field=models.CharField(max_length=150, unique=True, validators=[dashboard.models.validate_no_spaces]),
        ),
    ]
