# Antes de migrar comentar el codigo de la adicion de categoria migrar luego descomentar makemigration y migrar nuevamente.

# Generated by Django 5.0.7 on 2025-05-20 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('category', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='category.category'),
        ),
    ]
